# 线性代数

In [1]:
import torch
from matplotlib.pyplot import axis

标量由一个元素的张量表示

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x - y, x * y, x / y, x ** y

(tensor([5.]), tensor([1.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

可以将向量视为标量的列表

In [3]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

可以通过下标索引访问任一元素

In [4]:
x[2]

tensor(2.)

访问张量长度

In [5]:
len(x)

4

访问张量形状

In [6]:
x.shape

torch.Size([4])

指定两个分量m和n创建一个形状为 m x n 的矩阵

In [7]:
A = torch.arange(20).reshape(4, 5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

矩阵的转置

In [8]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

对称矩阵

In [9]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B.T == B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

同样可以构建具有更多轴的数据结构

In [11]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算姐u哦都将是相同形状的张量

In [12]:
A = torch.arange(20).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分给B
A, A + B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]))

两个矩阵的按元素乘法成为哈达玛积

In [13]:
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X + a, (X + a).shape  # 张量和标量的操作，即张量中每个元素都与标量进行计算操作

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算元素和

In [15]:
X = torch.arange(4, dtype=torch.float32)
X, X.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [16]:
A.shape, A.sum()  # 无论张量什么形状，其求和后都是标量

(torch.Size([5, 4]), tensor(190))

In [17]:
A = torch.arange(40, dtype=torch.float32).reshape(2, 5, 4)
A, A.shape, A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

指定求和汇总张量的轴

In [18]:
A_sum_axis0 = A.sum(axis=0)  # 按照一个维度求和
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [19]:
A.sum(axis=[0, 1])

tensor([180., 190., 200., 210.])

一个与求和相关的量是平均值（mean/average）

In [20]:
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [21]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

计算综合或均值时保持轴数不变

In [22]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

这种方式可以通过广播将A除以sum_A

In [23]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

计算某个轴的累计总和

In [24]:
A.cumsum(axis=1)

tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   6.,   8.,  10.],
         [ 12.,  15.,  18.,  21.],
         [ 24.,  28.,  32.,  36.],
         [ 40.,  45.,  50.,  55.]],

        [[ 20.,  21.,  22.,  23.],
         [ 44.,  46.,  48.,  50.],
         [ 72.,  75.,  78.,  81.],
         [104., 108., 112., 116.],
         [140., 145., 150., 155.]]])

点积是相同位置按照元素乘积的和

In [25]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行元素乘法再求和达到点乘效果

In [26]:
torch.sum((x * y))

tensor(6.)

矩阵向量积Ax是一个长度为m的列向量，其$i^{th}$元素是点积$a_i^Tx$

In [27]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法AB看作是简单执行m次矩阵-向量积，并将结果拼接再一起，形成一个 n x m 矩阵

In [28]:
B = torch.arange(12, dtype=torch.float32).reshape(4, 3)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([[ 42.,  48.,  54.],
         [114., 136., 158.],
         [186., 224., 262.],
         [258., 312., 366.],
         [330., 400., 470.]]))

$L_2$范数是向量元素平方和的平方根
$$
||x||_2 = \sqrt{\sum_{i=1}^n x_i^2}
$$

In [29]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$范数是向量元素的绝对值之和
$$
||x||_1=\sum_{i=1}^n |x_i|
$$

In [30]:
torch.abs(u).sum()

tensor(7.)

矩阵的 佛罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根
$$
||X||_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}
$$

In [31]:
torch.nrom(A)

tensor(49.6991)