In [16]:
import torch

In [17]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

In [18]:
x.requires_grad_(True)  # 等价于 x = torch.arange(4, dtype=torch.float32, requires_grad=True)
x.grad

In [19]:
# 计算y
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [20]:
# 通过调用反向传播函数自动计算y关于x每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [21]:
x.grad == 4 * x

tensor([True, True, True, True])

In [22]:
# 在默认情况下，PyTorch会累积梯度，偶们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [23]:
x.grad.zero_()
y = x * x
# 等价与 y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [26]:
x.grad.zero_()
y = x * x
u = y.detach()  # 将某些计算移动到记录的计算图之外
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [27]:
# 即使构建函数的计算图需要通过Python控制流，我们仍然可以计算得到变量的梯度
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c


a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(True)